name: Build and Release

on: 
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    env:
      PROJECT_NAME: 'blockcore-ws'

    steps:

    - uses: actions/checkout@master
      name: Checkout

    - uses: actions/setup-node@v2
      with:
        node-version: 18
        registry-url: 'https://registry.npmjs.org'

    - name: Variables
      run: |
        echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      shell: bash

    - name: Package Name
      run: |
        echo RELEASE_NAME=${{ env.PROJECT_NAME }}-${{ env.VERSION }}.tgz >> $GITHUB_ENV
      shell: bash

    - name: Install Packages
      run: |
        npm install

    - uses: actions/upload-artifact@v1
      with:
        name: ${{env.PROJECT_NAME}}-preview-${{env.VERSION}}
        path: "${{env.RELEASE_NAME}}"

    - name: Release
      uses: sondreb/action-release@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        files: "${{env.RELEASE_NAME}}"
        draft: true
        prerelease: false
        name: "Blockcore Websocket (${{env.VERSION}})"
        tag: ${{env.VERSION}}